// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<string>;

export function GetActiveSession():Promise<string>;

export function GetCurrentMode():Promise<string>;

export function GetModes():Promise<Array<main.SessionMode>>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function SetMode(arg1:string):Promise<void>;

export function StartTerminalListeners():Promise<void>;

export function SubmitReview(arg1:Array<main.ReviewComment>):Promise<void>;

export function SwitchSession(arg1:string):Promise<void>;
