// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentMode() {
  return window['go']['main']['App']['GetCurrentMode']();
}

export function GetModes() {
  return window['go']['main']['App']['GetModes']();
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SubmitReview(arg1) {
  return window['go']['main']['App']['SubmitReview'](arg1);
}
