// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {automation} from '../models';
import {backend} from '../models';
import {main} from '../models';

export function BrowseDirectory():Promise<string>;

export function CancelAutomationRun(arg1:string):Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function CreateAutomation(arg1:automation.Automation):Promise<automation.Automation>;

export function CreateSession(arg1:string):Promise<string>;

export function DeleteAutomation(arg1:string):Promise<void>;

export function GetActiveSession():Promise<string>;

export function GetAutomation(arg1:string):Promise<automation.Automation>;

export function GetAutomationRuns(arg1:string):Promise<Array<automation.Run>>;

export function GetCurrentMode():Promise<string>;

export function GetModes():Promise<Array<backend.SessionMode>>;

export function GetRunDetail(arg1:string,arg2:string):Promise<automation.Run>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function GetTriageItems():Promise<Array<automation.Run>>;

export function ListAutomations():Promise<Array<automation.Automation>>;

export function MarkRunRead(arg1:string,arg2:string):Promise<void>;

export function RunAutomationNow(arg1:string):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function StartTerminalListeners():Promise<void>;

export function SubmitReview(arg1:Array<main.ReviewComment>):Promise<void>;

export function SwitchSession(arg1:string):Promise<void>;

export function UpdateAutomation(arg1:automation.Automation):Promise<automation.Automation>;
