// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDirectory() {
  return window['go']['main']['App']['BrowseDirectory']();
}

export function CancelAutomationRun(arg1) {
  return window['go']['main']['App']['CancelAutomationRun'](arg1);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function CreateAutomation(arg1) {
  return window['go']['main']['App']['CreateAutomation'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteAutomation(arg1) {
  return window['go']['main']['App']['DeleteAutomation'](arg1);
}

export function GetActiveSession() {
  return window['go']['main']['App']['GetActiveSession']();
}

export function GetAutomation(arg1) {
  return window['go']['main']['App']['GetAutomation'](arg1);
}

export function GetAutomationRuns(arg1) {
  return window['go']['main']['App']['GetAutomationRuns'](arg1);
}

export function GetCurrentMode() {
  return window['go']['main']['App']['GetCurrentMode']();
}

export function GetModes() {
  return window['go']['main']['App']['GetModes']();
}

export function GetRunDetail(arg1, arg2) {
  return window['go']['main']['App']['GetRunDetail'](arg1, arg2);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetTriageItems() {
  return window['go']['main']['App']['GetTriageItems']();
}

export function ListAutomations() {
  return window['go']['main']['App']['ListAutomations']();
}

export function MarkRunRead(arg1, arg2) {
  return window['go']['main']['App']['MarkRunRead'](arg1, arg2);
}

export function RunAutomationNow(arg1) {
  return window['go']['main']['App']['RunAutomationNow'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function StartTerminalListeners() {
  return window['go']['main']['App']['StartTerminalListeners']();
}

export function SubmitReview(arg1) {
  return window['go']['main']['App']['SubmitReview'](arg1);
}

export function SwitchSession(arg1) {
  return window['go']['main']['App']['SwitchSession'](arg1);
}

export function UpdateAutomation(arg1) {
  return window['go']['main']['App']['UpdateAutomation'](arg1);
}
