// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentMode():Promise<string>;

export function GetModes():Promise<Array<main.SessionMode>>;

export function SetMode(arg1:string):Promise<void>;

export function SubmitReview(arg1:Array<main.ReviewComment>):Promise<void>;
